<?php
/**
 * CardDesign Class
 *
 * Manages a user's saved business card designs.
 *
 * Each design stores:
 *   - Which template it started from (template_id, nullable)
 *   - The card size key (e.g. 'standard_us')
 *   - A full content JSON snapshot (same shape as CardTemplate::blankContent())
 *     covering both the front face and an optional back face
 *   - A thumbnail path (PNG, generated by the editor canvas on save)
 *
 * Content JSON shape (extends CardTemplate content)
 * -------------------------------------------------
 * {
 *   "front": { ...same as CardTemplate content... },
 *   "back":  { ...same shape, or null if back not used... }
 * }
 */

require_once __DIR__ . '/CardTemplate.php';

class CardDesign {
    private static $db = null;

    private static function init() {
        if (self::$db === null) {
            self::$db = Database::getInstance();
        }
    }

    // ------------------------------------------------------------------
    // Create
    // ------------------------------------------------------------------

    /**
     * Create a new card design for a user.
     *
     * @param  int    $userId
     * @param  array  $data   Keys:
     *                          title           string  (default 'Untitled Card')
     *                          size_key        string  (default 'standard_us')
     *                          template_id     int|null
     *                          content         array   {front: {...}, back: null|{...}}
     *                          thumbnail_path  string|null
     * @return array  ['success' => bool, 'message' => string, 'id' => int|null]
     */
    public static function create($userId, $data) {
        self::init();

        $title      = isset($data['title'])       ? trim($data['title'])    : 'Untitled Card';
        $sizeKey    = isset($data['size_key'])     ? $data['size_key']      : 'standard_us';
        $templateId = isset($data['template_id']) ? (int)$data['template_id'] : null;
        $content    = $data['content']            ?? self::defaultContent();
        $thumbnail  = $data['thumbnail_path']     ?? null;

        if (empty($title)) {
            return ['success' => false, 'message' => 'Design title is required', 'id' => null];
        }

        $validation = self::validateContent($content);
        if (!$validation['valid']) {
            return ['success' => false, 'message' => $validation['message'], 'id' => null];
        }

        if (!array_key_exists($sizeKey, CARD_SIZES)) {
            return ['success' => false, 'message' => "Unknown card size: '$sizeKey'", 'id' => null];
        }

        try {
            $id = self::$db->insert('card_designs', [
                'user_id'        => (int)$userId,
                'template_id'    => $templateId,
                'title'          => $title,
                'size_key'       => $sizeKey,
                'content_json'   => json_encode($content, JSON_UNESCAPED_UNICODE),
                'thumbnail_path' => $thumbnail,
                'is_deleted'     => 0,
            ]);

            logActivity($userId, 'create', 'card_design', $id, "Created card design: $title");

            return ['success' => true, 'message' => 'Card design created', 'id' => $id];

        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Failed to create design: ' . $e->getMessage(), 'id' => null];
        }
    }

    /**
     * Create a new design pre-populated from a template.
     *
     * @param  int    $userId
     * @param  int    $templateId
     * @param  string $sizeKey     Override the template's default size if needed
     * @return array  Same return shape as create()
     */
    public static function createFromTemplate($userId, $templateId, $sizeKey = null) {
        $template = CardTemplate::getById($templateId);

        if (!$template) {
            return ['success' => false, 'message' => 'Template not found', 'id' => null];
        }

        $resolvedSize = $sizeKey ?? $template['default_size_key'];

        return self::create($userId, [
            'title'       => 'Untitled Card',
            'size_key'    => $resolvedSize,
            'template_id' => $templateId,
            'content'     => [
                'front' => $template['content'],
                'back'  => null,
            ],
        ]);
    }

    // ------------------------------------------------------------------
    // Read
    // ------------------------------------------------------------------

    /**
     * Get all non-deleted designs for a user, newest first.
     *
     * @param  int         $userId
     * @param  string|null $search  Optional title search
     * @return array[]
     */
    public static function getByUser($userId, $search = null) {
        self::init();

        if ($search) {
            $rows = self::$db->fetchAll(
                'SELECT id, user_id, template_id, title, size_key,
                        thumbnail_path, created_at, updated_at
                 FROM card_designs
                 WHERE user_id = ? AND is_deleted = 0 AND title LIKE ?
                 ORDER BY updated_at DESC',
                [(int)$userId, '%' . $search . '%']
            );
        } else {
            $rows = self::$db->fetchAll(
                'SELECT id, user_id, template_id, title, size_key,
                        thumbnail_path, created_at, updated_at
                 FROM card_designs
                 WHERE user_id = ? AND is_deleted = 0
                 ORDER BY updated_at DESC',
                [(int)$userId]
            );
        }

        // Attach human-readable size label to each row
        return array_map(function ($row) {
            $size = getCardSize($row['size_key']);
            $row['size_label'] = $size['label'] ?? $row['size_key'];
            return $row;
        }, $rows);
    }

    /**
     * Get a single design by ID (ownership-checked).
     * Includes decoded content and size config.
     *
     * @param  int        $designId
     * @param  int        $userId
     * @return array|null
     */
    public static function getById($designId, $userId) {
        self::init();

        $row = self::$db->fetchOne(
            'SELECT * FROM card_designs
             WHERE id = ? AND user_id = ? AND is_deleted = 0',
            [(int)$designId, (int)$userId]
        );

        return $row ? self::decode($row) : null;
    }

    /**
     * Count how many designs a user has (for dashboard display).
     *
     * @param  int $userId
     * @return int
     */
    public static function countByUser($userId) {
        self::init();

        $row = self::$db->fetchOne(
            'SELECT COUNT(*) as cnt FROM card_designs WHERE user_id = ? AND is_deleted = 0',
            [(int)$userId]
        );

        return (int)($row['cnt'] ?? 0);
    }

    // ------------------------------------------------------------------
    // Update
    // ------------------------------------------------------------------

    /**
     * Save the editor state (content + optional thumbnail).
     * Called by the auto-save and manual save triggers.
     *
     * @param  int        $designId
     * @param  int        $userId
     * @param  array      $content        {front: {...}, back: null|{...}}
     * @param  string|null $thumbnailPath  New thumbnail path, or null to leave unchanged
     * @return array  ['success' => bool, 'message' => string]
     */
    public static function save($designId, $userId, $content, $thumbnailPath = null) {
        self::init();

        // Ownership check
        $existing = self::$db->fetchOne(
            'SELECT id FROM card_designs WHERE id = ? AND user_id = ? AND is_deleted = 0',
            [(int)$designId, (int)$userId]
        );

        if (!$existing) {
            return ['success' => false, 'message' => 'Design not found or access denied'];
        }

        $validation = self::validateContent($content);
        if (!$validation['valid']) {
            return ['success' => false, 'message' => $validation['message']];
        }

        $fields = [
            'content_json' => json_encode($content, JSON_UNESCAPED_UNICODE),
            'updated_at'   => date('Y-m-d H:i:s'),
        ];

        if ($thumbnailPath !== null) {
            $fields['thumbnail_path'] = $thumbnailPath;
        }

        try {
            self::$db->update('card_designs', $fields, 'id = ? AND user_id = ?', [(int)$designId, (int)$userId]);
            return ['success' => true, 'message' => 'Design saved'];
        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Save failed: ' . $e->getMessage()];
        }
    }

    /**
     * Rename a design.
     *
     * @param  int    $designId
     * @param  int    $userId
     * @param  string $newTitle
     * @return array  ['success' => bool, 'message' => string]
     */
    public static function rename($designId, $userId, $newTitle) {
        self::init();

        $newTitle = trim($newTitle);
        if (empty($newTitle)) {
            return ['success' => false, 'message' => 'Title cannot be empty'];
        }

        $existing = self::$db->fetchOne(
            'SELECT id FROM card_designs WHERE id = ? AND user_id = ? AND is_deleted = 0',
            [(int)$designId, (int)$userId]
        );

        if (!$existing) {
            return ['success' => false, 'message' => 'Design not found or access denied'];
        }

        try {
            self::$db->update(
                'card_designs',
                ['title' => $newTitle, 'updated_at' => date('Y-m-d H:i:s')],
                'id = ? AND user_id = ?',
                [(int)$designId, (int)$userId]
            );
            return ['success' => true, 'message' => 'Design renamed'];
        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Rename failed: ' . $e->getMessage()];
        }
    }

    /**
     * Change the card size of a design (resizing does not modify element positions —
     * the editor handles re-scaling as percentages are size-independent).
     *
     * @param  int    $designId
     * @param  int    $userId
     * @param  string $newSizeKey
     * @return array  ['success' => bool, 'message' => string]
     */
    public static function changeSize($designId, $userId, $newSizeKey) {
        self::init();

        if (!array_key_exists($newSizeKey, CARD_SIZES)) {
            return ['success' => false, 'message' => "Unknown card size: '$newSizeKey'"];
        }

        $existing = self::$db->fetchOne(
            'SELECT id FROM card_designs WHERE id = ? AND user_id = ? AND is_deleted = 0',
            [(int)$designId, (int)$userId]
        );

        if (!$existing) {
            return ['success' => false, 'message' => 'Design not found or access denied'];
        }

        try {
            self::$db->update(
                'card_designs',
                ['size_key' => $newSizeKey, 'updated_at' => date('Y-m-d H:i:s')],
                'id = ? AND user_id = ?',
                [(int)$designId, (int)$userId]
            );
            return ['success' => true, 'message' => 'Card size updated'];
        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Size change failed: ' . $e->getMessage()];
        }
    }

    // ------------------------------------------------------------------
    // Duplicate & Delete
    // ------------------------------------------------------------------

    /**
     * Duplicate a design (owned by the same user).
     * Creates a new record with " (Copy)" appended to the title.
     *
     * @param  int   $designId
     * @param  int   $userId
     * @return array ['success' => bool, 'message' => string, 'id' => int|null]
     */
    public static function duplicate($designId, $userId) {
        self::init();

        $original = self::getById($designId, $userId);
        if (!$original) {
            return ['success' => false, 'message' => 'Design not found or access denied', 'id' => null];
        }

        $newTitle = $original['title'] . ' (Copy)';

        try {
            $newId = self::$db->insert('card_designs', [
                'user_id'        => (int)$userId,
                'template_id'    => $original['template_id'],
                'title'          => $newTitle,
                'size_key'       => $original['size_key'],
                'content_json'   => $original['content_json'],
                'thumbnail_path' => $original['thumbnail_path'],
                'is_deleted'     => 0,
            ]);

            logActivity($userId, 'duplicate', 'card_design', $newId, "Duplicated: {$original['title']}");

            return ['success' => true, 'message' => 'Design duplicated', 'id' => $newId];

        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Duplicate failed: ' . $e->getMessage(), 'id' => null];
        }
    }

    /**
     * Soft-delete a design (sets is_deleted = 1).
     * The record is kept in the DB so thumbnails remain reachable
     * until a scheduled hard-delete sweep runs.
     *
     * @param  int   $designId
     * @param  int   $userId
     * @return array ['success' => bool, 'message' => string]
     */
    public static function delete($designId, $userId) {
        self::init();

        $existing = self::$db->fetchOne(
            'SELECT id, title FROM card_designs WHERE id = ? AND user_id = ? AND is_deleted = 0',
            [(int)$designId, (int)$userId]
        );

        if (!$existing) {
            return ['success' => false, 'message' => 'Design not found or access denied'];
        }

        try {
            self::$db->update(
                'card_designs',
                ['is_deleted' => 1, 'updated_at' => date('Y-m-d H:i:s')],
                'id = ? AND user_id = ?',
                [(int)$designId, (int)$userId]
            );

            logActivity($userId, 'delete', 'card_design', $designId, "Deleted: {$existing['title']}");

            return ['success' => true, 'message' => 'Design deleted'];

        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Delete failed: ' . $e->getMessage()];
        }
    }

    // ------------------------------------------------------------------
    // Internal helpers
    // ------------------------------------------------------------------

    /**
     * Decode a raw DB row: parse content_json, attach size config.
     */
    private static function decode($row) {
        $row['content']    = json_decode($row['content_json'], true) ?? self::defaultContent();
        $row['size']       = getCardSize($row['size_key']);
        $row['size_label'] = $row['size']['label'] ?? $row['size_key'];
        return $row;
    }

    /**
     * Validate a design content array.
     * Must have a 'front' key; 'back' is optional (null is fine).
     *
     * @return array ['valid' => bool, 'message' => string]
     */
    private static function validateContent($content) {
        if (!is_array($content)) {
            return ['valid' => false, 'message' => 'Content must be an array'];
        }
        if (!isset($content['front']) || !is_array($content['front'])) {
            return ['valid' => false, 'message' => "Content must have a 'front' face array"];
        }
        if (!isset($content['front']['texts']) || !is_array($content['front']['texts'])) {
            return ['valid' => false, 'message' => "Front face must have a 'texts' array"];
        }
        return ['valid' => true, 'message' => ''];
    }

    /**
     * Return a blank two-face content structure.
     */
    private static function defaultContent() {
        $face = CardTemplate::blankContent();
        return ['front' => $face, 'back' => null];
    }
}
